#!/bin/bash
#t cd /home/lbmv/JGMC_copias/FrutoHass/filtro1
#t var=$(date); echo "Comenzó Alineamiento LSU FH f1[ $var]">> "Resumen.txt";
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz FH0_1_UP_fail_f1.fq.gz --al-gz FH0_1_UP_ali_f1.fq.gz --un-conc-gz FH0_1_PO_fail_f1.fq.gz --al-conc-gz FH0_1_PO_ali_f1.fq.gz --summary-file FH0_1_res_f1.txt --met-file FH0_1_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH0_1_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH0_1_R2_T_PO.cor.fq.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz FH0_2_UP_fail_f1.fq.gz --al-gz FH0_2_UP_ali_f1.fq.gz --un-conc-gz FH0_2_PO_fail_f1.fq.gz --al-conc-gz FH0_2_PO_ali_f1.fq.gz --summary-file FH0_2_res_f1.txt --met-file FH0_2_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH0_2_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH0_2_R2_T_PO.cor.fq.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz FH0_3_UP_fail_f1.fq.gz --al-gz FH0_3_UP_ali_f1.fq.gz --un-conc-gz FH0_3_PO_fail_f1.fq.gz --al-conc-gz FH0_3_PO_ali_f1.fq.gz --summary-file FH0_3_res_f1.txt --met-file FH0_3_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH0_3_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH0_3_R2_T_PO.cor.fq.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz FH1_1_UP_fail_f1.fq.gz --al-gz FH1_1_UP_ali_f1.fq.gz --un-conc-gz FH1_1_PO_fail_f1.fq.gz --al-conc-gz FH1_1_PO_ali_f1.fq.gz --summary-file FH1_1_res_f1.txt --met-file FH1_1_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH1_1_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH1_1_R2_T_PO.cor.fq.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz FH1_2_UP_fail_f1.fq.gz --al-gz FH1_2_UP_ali_f1.fq.gz --un-conc-gz FH1_2_PO_fail_f1.fq.gz --al-conc-gz FH1_2_PO_ali_f1.fq.gz --summary-file FH1_2_res_f1.txt --met-file FH1_2_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH1_2_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH1_2_R2_T_PO.cor.fq.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz FH1_3_UP_fail_f1.fq.gz --al-gz FH1_3_UP_ali_f1.fq.gz --un-conc-gz FH1_3_PO_fail_f1.fq.gz --al-conc-gz FH1_3_PO_ali_f1.fq.gz --summary-file FH1_3_res_f1.txt --met-file FH1_3_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH1_3_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH1_3_R2_T_PO.cor.fq.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz FH24_1_UP_fail_f1.fq.gz --al-gz FH24_1_UP_ali_f1.fq.gz --un-conc-gz FH24_1_PO_fail_f1.fq.gz --al-conc-gz FH24_1_PO_ali_f1.fq.gz --summary-file FH24_1_res_f1.txt --met-file FH24_1_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH24_1_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH24_1_R2_T_PO.cor.fq.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz FH24_2_UP_fail_f1.fq.gz --al-gz FH24_2_UP_ali_f1.fq.gz --un-conc-gz FH24_2_PO_fail_f1.fq.gz --al-conc-gz FH24_2_PO_ali_f1.fq.gz --summary-file FH24_2_res_f1.txt --met-file FH24_2_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH24_2_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH24_2_R2_T_PO.cor.fq.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz FH24_3_UP_fail_f1.fq.gz --al-gz FH24_3_UP_ali_f1.fq.gz --un-conc-gz FH24_3_PO_fail_f1.fq.gz --al-conc-gz FH24_3_PO_ali_f1.fq.gz --summary-file FH24_3_res_f1.txt --met-file FH24_3_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH24_3_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH24_3_R2_T_PO.cor.fq.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz FH72_1_UP_fail_f1.fq.gz --al-gz FH72_1_UP_ali_f1.fq.gz --un-conc-gz FH72_1_PO_fail_f1.fq.gz --al-conc-gz FH72_1_PO_ali_f1.fq.gz --summary-file FH72_1_res_f1.txt --met-file FH72_1_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH72_1_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH72_1_R2_T_PO.cor.fq.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz FH72_2_UP_fail_f1.fq.gz --al-gz FH72_2_UP_ali_f1.fq.gz --un-conc-gz FH72_2_PO_fail_f1.fq.gz --al-conc-gz FH72_2_PO_ali_f1.fq.gz --summary-file FH72_2_res_f1.txt --met-file FH72_2_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH72_2_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH72_2_R2_T_PO.cor.fq.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz FH72_3_UP_fail_f1.fq.gz --al-gz FH72_3_UP_ali_f1.fq.gz --un-conc-gz FH72_3_PO_fail_f1.fq.gz --al-conc-gz FH72_3_PO_ali_f1.fq.gz --summary-file FH72_3_res_f1.txt --met-file FH72_3_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH72_3_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoHass/seqCorre/unfixrm_FH72_3_R2_T_PO.cor.fq.gz
#t var=$(date); echo "Terminó Alinemaiento LSU FH f1[ $var]">> "Resumen.txt";
#t cd /home/lbmv/JGMC_copias/FrutoHass/filtro2
#t var=$(date); echo "Comenzó Alineamiento LSU FH f2[ $var]">> "Resumen.txt";
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz FH0_1_UP_fail_f2.fq.gz --al-gz FH0_1_UP_ali_f2.fq.gz --un-conc-gz FH0_1_PO_fail_f2.fq.gz --al-conc-gz FH0_1_PO_ali_f2.fq.gz --summary-file FH0_1_res_f2.txt --met-file FH0_1_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH0_1_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH0_1_PO_fail_f1.fq.2.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz FH0_2_UP_fail_f2.fq.gz --al-gz FH0_2_UP_ali_f2.fq.gz --un-conc-gz FH0_2_PO_fail_f2.fq.gz --al-conc-gz FH0_2_PO_ali_f2.fq.gz --summary-file FH0_2_res_f2.txt --met-file FH0_2_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH0_2_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH0_2_PO_fail_f1.fq.2.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz FH0_3_UP_fail_f2.fq.gz --al-gz FH0_3_UP_ali_f2.fq.gz --un-conc-gz FH0_3_PO_fail_f2.fq.gz --al-conc-gz FH0_3_PO_ali_f2.fq.gz --summary-file FH0_3_res_f2.txt --met-file FH0_3_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH0_3_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH0_3_PO_fail_f1.fq.2.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz FH1_1_UP_fail_f2.fq.gz --al-gz FH1_1_UP_ali_f2.fq.gz --un-conc-gz FH1_1_PO_fail_f2.fq.gz --al-conc-gz FH1_1_PO_ali_f2.fq.gz --summary-file FH1_1_res_f2.txt --met-file FH1_1_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH1_1_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH1_1_PO_fail_f1.fq.2.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz FH1_2_UP_fail_f2.fq.gz --al-gz FH1_2_UP_ali_f2.fq.gz --un-conc-gz FH1_2_PO_fail_f2.fq.gz --al-conc-gz FH1_2_PO_ali_f2.fq.gz --summary-file FH1_2_res_f2.txt --met-file FH1_2_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH1_2_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH1_2_PO_fail_f1.fq.2.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz FH1_3_UP_fail_f2.fq.gz --al-gz FH1_3_UP_ali_f2.fq.gz --un-conc-gz FH1_3_PO_fail_f2.fq.gz --al-conc-gz FH1_3_PO_ali_f2.fq.gz --summary-file FH1_3_res_f2.txt --met-file FH1_3_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH1_3_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH1_3_PO_fail_f1.fq.2.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz FH24_1_UP_fail_f2.fq.gz --al-gz FH24_1_UP_ali_f2.fq.gz --un-conc-gz FH24_1_PO_fail_f2.fq.gz --al-conc-gz FH24_1_PO_ali_f2.fq.gz --summary-file FH24_1_res_f2.txt --met-file FH24_1_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH24_1_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH24_1_PO_fail_f1.fq.2.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz FH24_2_UP_fail_f2.fq.gz --al-gz FH24_2_UP_ali_f2.fq.gz --un-conc-gz FH24_2_PO_fail_f2.fq.gz --al-conc-gz FH24_2_PO_ali_f2.fq.gz --summary-file FH24_2_res_f2.txt --met-file FH24_2_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH24_2_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH24_2_PO_fail_f1.fq.2.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz FH24_3_UP_fail_f2.fq.gz --al-gz FH24_3_UP_ali_f2.fq.gz --un-conc-gz FH24_3_PO_fail_f2.fq.gz --al-conc-gz FH24_3_PO_ali_f2.fq.gz --summary-file FH24_3_res_f2.txt --met-file FH24_3_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH24_3_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH24_3_PO_fail_f1.fq.2.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz FH72_1_UP_fail_f2.fq.gz --al-gz FH72_1_UP_ali_f2.fq.gz --un-conc-gz FH72_1_PO_fail_f2.fq.gz --al-conc-gz FH72_1_PO_ali_f2.fq.gz --summary-file FH72_1_res_f2.txt --met-file FH72_1_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH72_1_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH72_1_PO_fail_f1.fq.2.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz FH72_2_UP_fail_f2.fq.gz --al-gz FH72_2_UP_ali_f2.fq.gz --un-conc-gz FH72_2_PO_fail_f2.fq.gz --al-conc-gz FH72_2_PO_ali_f2.fq.gz --summary-file FH72_2_res_f2.txt --met-file FH72_2_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH72_2_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH72_2_PO_fail_f1.fq.2.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz FH72_3_UP_fail_f2.fq.gz --al-gz FH72_3_UP_ali_f2.fq.gz --un-conc-gz FH72_3_PO_fail_f2.fq.gz --al-conc-gz FH72_3_PO_ali_f2.fq.gz --summary-file FH72_3_res_f2.txt --met-file FH72_3_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH72_3_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoHass/filtro1/FH72_3_PO_fail_f1.fq.2.gz
#t var=$(date); echo "Terminó Alinemaiento LSU FH[ $var] f2">> "Resumen.txt";
#cd /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1
#var=$(date); echo "Comenzó Alineamiento LSU F f1 faltante2 [ $var]">> "Resumen.txt";
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz F0_1_UP_fail_f1.fq.gz --al-gz F0_1_UP_ali_f1.fq.gz --un-conc-gz F0_1_PO_fail_f1.fq.gz --al-conc-gz F0_1_PO_ali_f1.fq.gz --summary-file F0_1_res_f1.txt --met-file F0_1_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F0_1_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F0_1_R2_T_PO.cor.fq.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz F0_2_UP_fail_f1.fq.gz --al-gz F0_2_UP_ali_f1.fq.gz --un-conc-gz F0_2_PO_fail_f1.fq.gz --al-conc-gz F0_2_PO_ali_f1.fq.gz --summary-file F0_2_res_f1.txt --met-file F0_2_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F0_2_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F0_2_R2_T_PO.cor.fq.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz F0_3_UP_fail_f1.fq.gz --al-gz F0_3_UP_ali_f1.fq.gz --un-conc-gz F0_3_PO_fail_f1.fq.gz --al-conc-gz F0_3_PO_ali_f1.fq.gz --summary-file F0_3_res_f1.txt --met-file F0_3_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F0_3_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F0_3_R2_T_PO.cor.fq.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz F1_1_UP_fail_f1.fq.gz --al-gz F1_1_UP_ali_f1.fq.gz --un-conc-gz F1_1_PO_fail_f1.fq.gz --al-conc-gz F1_1_PO_ali_f1.fq.gz --summary-file F1_1_res_f1.txt --met-file F1_1_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F1_1_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F1_1_R2_T_PO.cor.fq.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz F1_2_UP_fail_f1.fq.gz --al-gz F1_2_UP_ali_f1.fq.gz --un-conc-gz F1_2_PO_fail_f1.fq.gz --al-conc-gz F1_2_PO_ali_f1.fq.gz --summary-file F1_2_res_f1.txt --met-file F1_2_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F1_2_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F1_2_R2_T_PO.cor.fq.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz F1_3_UP_fail_f1.fq.gz --al-gz F1_3_UP_ali_f1.fq.gz --un-conc-gz F1_3_PO_fail_f1.fq.gz --al-conc-gz F1_3_PO_ali_f1.fq.gz --summary-file F1_3_res_f1.txt --met-file F1_3_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F1_3_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F1_3_R2_T_PO.cor.fq.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz F24_1_UP_fail_f1.fq.gz --al-gz F24_1_UP_ali_f1.fq.gz --un-conc-gz F24_1_PO_fail_f1.fq.gz --al-conc-gz F24_1_PO_ali_f1.fq.gz --summary-file F24_1_res_f1.txt --met-file F24_1_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F24_1_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F24_1_R2_T_PO.cor.fq.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz F24_2_UP_fail_f1.fq.gz --al-gz F24_2_UP_ali_f1.fq.gz --un-conc-gz F24_2_PO_fail_f1.fq.gz --al-conc-gz F24_2_PO_ali_f1.fq.gz --summary-file F24_2_res_f1.txt --met-file F24_2_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F24_2_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F24_2_R2_T_PO.cor.fq.gz
#hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz F24_3_UP_fail_f1.fq.gz --al-gz F24_3_UP_ali_f1.fq.gz --un-conc-gz F24_3_PO_fail_f1.fq.gz --al-conc-gz F24_3_PO_ali_f1.fq.gz --summary-file F24_3_res_f1.txt --met-file F24_3_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F24_3_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F24_3_R2_T_PO.cor.fq.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz F72_1_UP_fail_f1.fq.gz --al-gz F72_1_UP_ali_f1.fq.gz --un-conc-gz F72_1_PO_fail_f1.fq.gz --al-conc-gz F72_1_PO_ali_f1.fq.gz --summary-file F72_1_res_f1.txt --met-file F72_1_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F72_1_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F72_1_R2_T_PO.cor.fq.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz F72_2_UP_fail_f1.fq.gz --al-gz F72_2_UP_ali_f1.fq.gz --un-conc-gz F72_2_PO_fail_f1.fq.gz --al-conc-gz F72_2_PO_ali_f1.fq.gz --summary-file F72_2_res_f1.txt --met-file F72_2_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F72_2_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F72_2_R2_T_PO.cor.fq.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/hisat2/LSU_DNA_Silva --reorder --un-gz F72_3_UP_fail_f1.fq.gz --al-gz F72_3_UP_ali_f1.fq.gz --un-conc-gz F72_3_PO_fail_f1.fq.gz --al-conc-gz F72_3_PO_ali_f1.fq.gz --summary-file F72_3_res_f1.txt --met-file F72_3_Hisat_metrics_f1.txt --fr -1 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F72_3_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F72_3_R2_T_PO.cor.fq.gz
#var=$(date); echo "Terminó Alinemaiento LSU F f1 faltante2 [ $var]">> "Resumen.txt";
cd /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro2
#var=$(date); echo "Comenzó Alineamiento LSU F f2 faltante [ $var]">> "Resumen.txt";
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz F0_1_UP_fail_f2.fq.gz --al-gz F0_1_UP_ali_f2.fq.gz --un-conc-gz F0_1_PO_fail_f2.fq.gz --al-conc-gz F0_1_PO_ali_f2.fq.gz --summary-file F0_1_res_f2.txt --met-file F0_1_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F0_1_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F0_1_PO_fail_f1.fq.2.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz F0_2_UP_fail_f2.fq.gz --al-gz F0_2_UP_ali_f2.fq.gz --un-conc-gz F0_2_PO_fail_f2.fq.gz --al-conc-gz F0_2_PO_ali_f2.fq.gz --summary-file F0_2_res_f2.txt --met-file F0_2_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F0_2_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F0_2_PO_fail_f1.fq.2.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz F0_3_UP_fail_f2.fq.gz --al-gz F0_3_UP_ali_f2.fq.gz --un-conc-gz F0_3_PO_fail_f2.fq.gz --al-conc-gz F0_3_PO_ali_f2.fq.gz --summary-file F0_3_res_f2.txt --met-file F0_3_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F0_3_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F0_3_PO_fail_f1.fq.2.gz
hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz F1_1_UP_fail_f2.fq.gz --al-gz F1_1_UP_ali_f2.fq.gz --un-conc-gz F1_1_PO_fail_f2.fq.gz --al-conc-gz F1_1_PO_ali_f2.fq.gz --summary-file F1_1_res_f2.txt --met-file F1_1_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F1_1_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F1_1_PO_fail_f1.fq.2.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz F1_2_UP_fail_f2.fq.gz --al-gz F1_2_UP_ali_f2.fq.gz --un-conc-gz F1_2_PO_fail_f2.fq.gz --al-conc-gz F1_2_PO_ali_f2.fq.gz --summary-file F1_2_res_f2.txt --met-file F1_2_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F1_2_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F1_2_PO_fail_f1.fq.2.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz F1_3_UP_fail_f2.fq.gz --al-gz F1_3_UP_ali_f2.fq.gz --un-conc-gz F1_3_PO_fail_f2.fq.gz --al-conc-gz F1_3_PO_ali_f2.fq.gz --summary-file F1_3_res_f2.txt --met-file F1_3_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F1_3_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F1_3_PO_fail_f1.fq.2.gz
#hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz F24_1_UP_fail_f2.fq.gz --al-gz F24_1_UP_ali_f2.fq.gz --un-conc-gz F24_1_PO_fail_f2.fq.gz --al-conc-gz F24_1_PO_ali_f2.fq.gz --summary-file F24_1_res_f2.txt --met-file F24_1_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F24_1_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F24_1_PO_fail_f1.fq.2.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz F24_2_UP_fail_f2.fq.gz --al-gz F24_2_UP_ali_f2.fq.gz --un-conc-gz F24_2_PO_fail_f2.fq.gz --al-conc-gz F24_2_PO_ali_f2.fq.gz --summary-file F24_2_res_f2.txt --met-file F24_2_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F24_2_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F24_2_PO_fail_f1.fq.2.gz
#hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz F24_3_UP_fail_f2.fq.gz --al-gz F24_3_UP_ali_f2.fq.gz --un-conc-gz F24_3_PO_fail_f2.fq.gz --al-conc-gz F24_3_PO_ali_f2.fq.gz --summary-file F24_3_res_f2.txt --met-file F24_3_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F24_3_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F24_3_PO_fail_f1.fq.2.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz F72_1_UP_fail_f2.fq.gz --al-gz F72_1_UP_ali_f2.fq.gz --un-conc-gz F72_1_PO_fail_f2.fq.gz --al-conc-gz F72_1_PO_ali_f2.fq.gz --summary-file F72_1_res_f2.txt --met-file F72_1_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F72_1_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F72_1_PO_fail_f1.fq.2.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz F72_2_UP_fail_f2.fq.gz --al-gz F72_2_UP_ali_f2.fq.gz --un-conc-gz F72_2_PO_fail_f2.fq.gz --al-conc-gz F72_2_PO_ali_f2.fq.gz --summary-file F72_2_res_f2.txt --met-file F72_2_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F72_2_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F72_2_PO_fail_f1.fq.2.gz
#t hisat2 --very-sensitive --phred33 --dta -p 8 -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/SSU/hisat2/SSU_DNA_Silva --reorder --un-gz F72_3_UP_fail_f2.fq.gz --al-gz F72_3_UP_ali_f2.fq.gz --un-conc-gz F72_3_PO_fail_f2.fq.gz --al-conc-gz F72_3_PO_ali_f2.fq.gz --summary-file F72_3_res_f2.txt --met-file F72_3_Hisat_metrics_f2.txt --fr -1 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F72_3_PO_fail_f1.fq.1.gz -2 /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro1/F72_3_PO_fail_f1.fq.2.gz
var=$(date); echo "Terminó Alinemaiento LSU F faltante [ $var] f2">> "Resumen.txt";
#t #Prueba con Bowtie
#t cd "/home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/bowtie";
#t var=$(date); echo "Comenzó Alineamiento LSU F f1 [ $var]">> "Resumen.txt";
#t bowtie2 --quiet --very-sensitive-local --phred33  -x /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/bowtie2/LSU_DNA_Silva_1 -1 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F0_1_R1_T_PO.cor.fq.gz -2 /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F0_1_R2_T_PO.cor.fq.gz --threads 8 --met-file F0_1_bowtie2_metrics.txt --al-conc-gz blacklist_paired_aligned_F0_1.fq.gz --un-conc-gz blacklist_paired_unaligned_F0_1.fq.gz --al-gz blacklist_unpaired_aligned_F0_1.fq.gz --un-gz blacklist_unpaired_unaligned_F0_1.fq.gz
#t var=$(date); echo "Terminó Alineamiento LSU F f1 [ $var]">> "Resumen.txt";
#Prueba con sortmerna
#t cd "/home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/sortmerna";
#t var=$(date); echo "Comenzó Alineamiento LSU F f1 [ $var]">> "Resumen.txt";
#t sortmerna --ref /home/lbmv/Resp_070921_JGMC/rRNA_ref/LSU/DNA_SILVA_138.1_LSUParc_tax_silva.fasta --reads /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F0_1_R1_T_PO.cor.fq.gz /home/lbmv/Resp_070921_JGMC/FrutoTratado/seqCorre/unfixrm_F0_1_R2_T_PO.cor.fq.gz >> Res
#t var=$(date); echo "Terminó Alineamiento LSU F f1 [ $var]">> "Resumen.txt";
#t #Descompresión de archivos
#t cd /home/lbmv/JGMC_copias/FrutoHass/filtro2/filtradosFH;
#t var=$(date); echo "Comenzó duplicado FH[ $var]">> "Resumen.txt";
#t cp * /home/lbmv/JGMC_copias/FrutoHass/filtro2/filtradosFH/ensamble
#t var=$(date); echo "Terminó duplicado FH[ $var]">> "Resumen.txt";
#t cd /home/lbmv/JGMC_copias/FrutoHass/filtro2/filtradosFH/ensamble
#t var=$(date); echo "Comenzó descompresión FH[ $var]">> "Resumen.txt";
#t gzip -d *fq.1.gz | gzip -d *fq.2.gz;
#t var=$(date); echo "Terminó descompresión FH[ $var]">> "Resumen.txt";
#t #Aqui empieza el del comando para Fruto Tratado
#t cd /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro2;
#t mv F*PO_ali_f2*.fq /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro2/filtradosF;
#t cd /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro2/filtradosF;
#t var=$(date); echo "Comenzó duplicado F[ $var]">> "Resumen.txt";
#t cp * /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro2/filtradosF/ensamble;
#t var=$(date); echo "Terminó duplicado F[ $var]">> "Resumen.txt";
#t cd /home/lbmv/JGMC_copias/FrutoTratado/pruebas_al/hisat2/filtro2/filtradosF/ensamble;
#t var=$(date); echo "Comenzó descompresión F[ $var]">> "Resumen.txt";
#t gzip -d *fq.1.gz | gzip -d *fq.2.gz;
#t var=$(date); echo "Terminó descompresión F[ $var]">> "Resumen.txt";

